# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 902ef055a9ac93f18327f1f9c45ab059f1a62c7d

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
Content-Type: application/json

###

GET {{baseUrl}}/favourites/
Content-Type: application/json
Authorization: Token 5c6181275bd35e576dfbea11fc63d567cd57c32e

###

POST {{baseUrl}}/favourites/
Content-Type: application/json
Authorization: Token 5c6181275bd35e576dfbea11fc63d567cd57c32e

{
  "advertisement": 5
}
